# Generated by Django 5.0.6 on 2024-07-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_movie_tmdb_id_alter_review_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(unique=True),
        ),
    ]
